<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="..\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Inventory.Contracts\Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks.Persistence\BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
