DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS inventory.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
            CREATE SCHEMA inventory;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE TABLE inventory.outbox_messages (
        "Id" uuid NOT NULL,
        "Type" character varying(300) NOT NULL,
        "Content" jsonb NOT NULL,
        "OccurredOnUtc" timestamp with time zone NOT NULL,
        "ProcessedOnUtc" timestamp with time zone,
        "Attempts" integer NOT NULL DEFAULT 0,
        "Error" character varying(2000),
        CONSTRAINT "PK_outbox_messages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE TABLE inventory.stock_items (
        "Id" uuid NOT NULL,
        "Sku" character varying(50) NOT NULL,
        "QuantityOnHand" integer NOT NULL,
        "QuantityReserved" integer NOT NULL,
        "UpdatedOnUtc" timestamp with time zone NOT NULL,
        "TenantId" uuid NOT NULL,
        CONSTRAINT "PK_stock_items" PRIMARY KEY ("Id"),
        CONSTRAINT ck_stock_items_on_hand_non_negative CHECK ("QuantityOnHand" >= 0),
        CONSTRAINT ck_stock_items_reserved_within_on_hand CHECK ("QuantityReserved" >= 0 AND "QuantityReserved" <= "QuantityOnHand")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE TABLE inventory.stock_reservations (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedOnUtc" timestamp with time zone NOT NULL,
        "ReleasedOnUtc" timestamp with time zone,
        "TenantId" uuid NOT NULL,
        CONSTRAINT "PK_stock_reservations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE TABLE inventory.stock_reservation_lines (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Sku" character varying(50) NOT NULL,
        "Quantity" integer NOT NULL,
        "ReservationId" uuid NOT NULL,
        CONSTRAINT "PK_stock_reservation_lines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_stock_reservation_lines_stock_reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES inventory.stock_reservations ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE INDEX ix_outbox_messages_unprocessed ON inventory.outbox_messages ("OccurredOnUtc") WHERE "ProcessedOnUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_stock_items_TenantId_Sku" ON inventory.stock_items ("TenantId", "Sku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE INDEX "IX_stock_reservation_lines_ReservationId" ON inventory.stock_reservation_lines ("ReservationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_stock_reservations_TenantId_OrderId" ON inventory.stock_reservations ("TenantId", "OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory.__ef_migrations_history WHERE "MigrationId" = '20260929124821_InitialCreate') THEN
    INSERT INTO inventory.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260929124821_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

