<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
    <ProjectReference Include="..\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks.Persistence\BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
