<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Reporting.Application\Reporting.Application.csproj" />
    <ProjectReference Include="..\Reporting.Infrastructure\Reporting.Infrastructure.csproj" />
    <ProjectReference Include="..\Reporting.Contracts\Reporting.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks.Persistence\BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
